version: "3"
services:
    database:
      image: mysql
      ports:
        - "3306"
      environment:
        - DEFAULT_AUTHENTICATION_PLUGIN=mysql_native_password
        - MYSQL_ROOT_PASSWORD="password"
        - MYSQL_DATABASE="movies"
      volumes:
        - ./sql/init:/docker-entrypoint-init.d
    api:
      build: ./api
      command: npm install
      depends_on:
        - database
      ports:
        - "49160:8080"  
