version: "3"
services:
    database:
      image: mysql
      command: --init-file /docker-entrypoint-init.d/script.sql
      ports:
        - "3306"
      environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=movies
        - MYSQL_USER='api'@'172.32.0.15'
      volumes:
        - ./sql/init:/docker-entrypoint-init.d
      networks:
        sqlbridge:
          ipv4_address: 172.32.0.3
    api:
      build: ./api
      ports:
        - "49160:8080"
      networks:
        sqlbridge:
          ipv4_address: 172.32.0.15
networks:
  sqlbridge:
    driver: bridge
    ipam:
     config:
       - subnet: 172.32.0.0/16
